name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: node:lts-alpine

    steps:
    - uses: actions/checkout@v3
    - name: install
    - run: npm i
    - run: cd client
    - run: npm i
    - run: npm run build
